$(document).ready(function(){
    $("#btn_ocultar").click(function(){
        $("p").hide();
    });
    $("#btn_mostrar").click(function(){
        $("p").show();
    });
    $("#btn_ocultar_despacio").click(function(){
        $("p").hide("slow");
    });
    $("#btn_mostrar_despacio").click(function(){
        $("p").show("slow");
    });
    $("#btn_ocultar_slide").click(function(){
        $("p").slideUp(2000);
    });
    $("#btn_mostrar_slide").click(function(){
        $("p").slideDown(2000);
    });
});